/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CloudExchangeEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ARBITRATOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "PAUSER_ROLE"
      | "REQUIRED_ADMIN_APPROVALS"
      | "TIMELOCK_DELAY"
      | "approveEmergencyWithdraw"
      | "cancelAndRefund"
      | "claimDisputeTimeout"
      | "createEscrow"
      | "emergencyApprovals"
      | "emergencyProposalCounter"
      | "emergencyProposals"
      | "escrowCounter"
      | "escrows"
      | "executeEmergencyWithdraw"
      | "feePercentage"
      | "feeRecipient"
      | "grantArbitrator"
      | "hasRole"
      | "initiateDispute"
      | "markPaid"
      | "pause"
      | "paused"
      | "proposeEmergencyWithdraw"
      | "releaseEscrow"
      | "resolveDispute"
      | "revokeArbitrator"
      | "unpause"
      | "updateFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdrawApproved"
      | "EmergencyWithdrawExecuted"
      | "EmergencyWithdrawProposed"
      | "EscrowCreated"
      | "EscrowDisputed"
      | "EscrowDisputedResolved"
      | "EscrowPaid"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "Paused"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ARBITRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUIRED_ADMIN_APPROVALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveEmergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAndRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDisputeTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyApprovals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyProposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantArbitrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markPaid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeEmergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeArbitrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFee",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ARBITRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUIRED_ADMIN_APPROVALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelAndRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDisputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyProposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markPaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateFee", data: BytesLike): Result;
}

export namespace EmergencyWithdrawApprovedEvent {
  export type InputTuple = [proposalId: BigNumberish, admin: AddressLike];
  export type OutputTuple = [proposalId: bigint, admin: string];
  export interface OutputObject {
    proposalId: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawExecutedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [proposalId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    proposalId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawProposedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [proposalId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    proposalId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    seller: AddressLike,
    buyer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    seller: string,
    buyer: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
    buyer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [escrowId: BigNumberish, initiatedBy: AddressLike];
  export type OutputTuple = [escrowId: bigint, initiatedBy: string];
  export interface OutputObject {
    escrowId: bigint;
    initiatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedResolvedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    winner: AddressLike,
    resolvedBy: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    winner: string,
    resolvedBy: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    winner: string;
    resolvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowPaidEvent {
  export type InputTuple = [escrowId: BigNumberish];
  export type OutputTuple = [escrowId: bigint];
  export interface OutputObject {
    escrowId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [escrowId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [escrowId: bigint, seller: string];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [escrowId: bigint, buyer: string];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CloudExchangeEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): CloudExchangeEscrow;
  waitForDeployment(): Promise<this>;

  interface: CloudExchangeEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ARBITRATOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REQUIRED_ADMIN_APPROVALS: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  approveEmergencyWithdraw: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelAndRefund: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimDisputeTimeout: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      _buyer: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _fiatAmount: BigNumberish,
      _paymentWindow: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyApprovals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  emergencyProposalCounter: TypedContractMethod<[], [bigint], "view">;

  emergencyProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        proposedAt: bigint;
        approvalCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  escrowCounter: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        seller: string;
        buyer: string;
        token: string;
        amount: bigint;
        fiatAmount: bigint;
        createdAt: bigint;
        paymentWindow: bigint;
        disputeTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  executeEmergencyWithdraw: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feePercentage: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  grantArbitrator: TypedContractMethod<
    [_arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initiateDispute: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  markPaid: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proposeEmergencyWithdraw: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  releaseEscrow: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [_escrowId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeArbitrator: TypedContractMethod<
    [_arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateFee: TypedContractMethod<
    [_newFeePercentage: BigNumberish, _newFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ARBITRATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REQUIRED_ADMIN_APPROVALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveEmergencyWithdraw"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelAndRefund"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDisputeTimeout"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      _buyer: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _fiatAmount: BigNumberish,
      _paymentWindow: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyApprovals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyProposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        proposedAt: bigint;
        approvalCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        seller: string;
        buyer: string;
        token: string;
        amount: bigint;
        fiatAmount: bigint;
        createdAt: bigint;
        paymentWindow: bigint;
        disputeTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeEmergencyWithdraw"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantArbitrator"
  ): TypedContractMethod<[_arbitrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateDispute"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markPaid"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposeEmergencyWithdraw"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeArbitrator"
  ): TypedContractMethod<[_arbitrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFee"
  ): TypedContractMethod<
    [_newFeePercentage: BigNumberish, _newFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmergencyWithdrawApproved"
  ): TypedContractEvent<
    EmergencyWithdrawApprovedEvent.InputTuple,
    EmergencyWithdrawApprovedEvent.OutputTuple,
    EmergencyWithdrawApprovedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawExecuted"
  ): TypedContractEvent<
    EmergencyWithdrawExecutedEvent.InputTuple,
    EmergencyWithdrawExecutedEvent.OutputTuple,
    EmergencyWithdrawExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawProposed"
  ): TypedContractEvent<
    EmergencyWithdrawProposedEvent.InputTuple,
    EmergencyWithdrawProposedEvent.OutputTuple,
    EmergencyWithdrawProposedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputedResolved"
  ): TypedContractEvent<
    EscrowDisputedResolvedEvent.InputTuple,
    EscrowDisputedResolvedEvent.OutputTuple,
    EscrowDisputedResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowPaid"
  ): TypedContractEvent<
    EscrowPaidEvent.InputTuple,
    EscrowPaidEvent.OutputTuple,
    EscrowPaidEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdrawApproved(uint256,address)": TypedContractEvent<
      EmergencyWithdrawApprovedEvent.InputTuple,
      EmergencyWithdrawApprovedEvent.OutputTuple,
      EmergencyWithdrawApprovedEvent.OutputObject
    >;
    EmergencyWithdrawApproved: TypedContractEvent<
      EmergencyWithdrawApprovedEvent.InputTuple,
      EmergencyWithdrawApprovedEvent.OutputTuple,
      EmergencyWithdrawApprovedEvent.OutputObject
    >;

    "EmergencyWithdrawExecuted(uint256,address,uint256)": TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;
    EmergencyWithdrawExecuted: TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;

    "EmergencyWithdrawProposed(uint256,address,uint256)": TypedContractEvent<
      EmergencyWithdrawProposedEvent.InputTuple,
      EmergencyWithdrawProposedEvent.OutputTuple,
      EmergencyWithdrawProposedEvent.OutputObject
    >;
    EmergencyWithdrawProposed: TypedContractEvent<
      EmergencyWithdrawProposedEvent.InputTuple,
      EmergencyWithdrawProposedEvent.OutputTuple,
      EmergencyWithdrawProposedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowDisputed(uint256,address)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowDisputedResolved(uint256,address,address)": TypedContractEvent<
      EscrowDisputedResolvedEvent.InputTuple,
      EscrowDisputedResolvedEvent.OutputTuple,
      EscrowDisputedResolvedEvent.OutputObject
    >;
    EscrowDisputedResolved: TypedContractEvent<
      EscrowDisputedResolvedEvent.InputTuple,
      EscrowDisputedResolvedEvent.OutputTuple,
      EscrowDisputedResolvedEvent.OutputObject
    >;

    "EscrowPaid(uint256)": TypedContractEvent<
      EscrowPaidEvent.InputTuple,
      EscrowPaidEvent.OutputTuple,
      EscrowPaidEvent.OutputObject
    >;
    EscrowPaid: TypedContractEvent<
      EscrowPaidEvent.InputTuple,
      EscrowPaidEvent.OutputTuple,
      EscrowPaidEvent.OutputObject
    >;

    "EscrowRefunded(uint256,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
